language: java
sudo: required
jdk:
  - openjdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh pcm2java releng/edu.kit.ipd.sdq.mdsd.pcm2java.updatesite.aggregated final KASTEL-SCBS updatesite

notifications:
  slack:
    secure: X1Xb5CDd91pZftRRsrNrJCSN8RqJwM9yA4TgXdeaGsM9F20fjcaivJwNLxM4FtJrMBkmHtQO0mn9FQz12BRyGbkUEjVXcx8PX2EBTBe0wQ4+KOfbytuKZagwVnelwQhYNDXgx7qS0OgKxuYqA5nVdRjVmKFmlemgOUFEbpiffmU1fV33VOxbZb09qnJ0mBB9wWjhtAUds+GHWwdRYnhH3zOIjKN/NvxEFrruQFVncQqtX+VUXrpWplB4OuEYb9CnNbtYIU50Ae5fgm0RPkYI3u9X6LapmqCdT7Zjvh5U+Gf9LyZ5UDThFAV7wiHSgw2JJJmjBDel2oo/NNH+wk8O8acMvsuhQqRsbJkfis+FCP4dMO5nsbn4JtG1KpCKQ6HaVSiEHxFoU903TeaARBYnIty5f6YlDj+tiGfRgTOagbfs0+UqiIeTHuilZxNryPwyyRAfOmjsskitpfSZ5kxLNeHittRwnFiemyAAusc/U3Srlm1za05mhE0tH55OOcD7Ehn0d/GqzHMID2V7VI/M3kjEpqmLH6nj3u06SN2tP73FUOqCUr3+pIAXUUOYeCnlN/YcoULKiqgRTLAIHvmAS5BDfei6JeeM9aCvmSgsGT1RpDv675WfSn6bg4z3hfCtgAuVxIlGu0uC2QHZgRmPWGzf0pC0BBU0MLr6GH/seRg=
